name: shadowsocksr build matrix - cmake

on: 
  push:
  release:
    types: [prereleased]

jobs:
  build:
    strategy:
      matrix:
        qt_version: [5.11.3, 5.14.2]
        platform: [ubuntu-16.04, macos-latest, windows-latest]
        arch: [x86, x64]
        include: 
          - platform: windows-latest
            arch: x86
            qtarch: win32_msvc2017
          - platform: windows-latest
            arch: x64
            qtarch: win64_msvc2017_64
        exclude:
          - platform: ubuntu-16.04
            arch: x86
          - platform: macos-latest
            arch: x86
          - platform: windows-latest
            qt_version: 5.11.3
      fail-fast: false
        
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Get the version
        id: get_version
        shell: bash
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Checking out sources
        uses: actions/checkout@master
      - name: Install Python 3.7 version
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: ${{ matrix.arch }}
# =========================================================================================================
      - name: Install MSVC compiler
        if: matrix.platform == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
        with: 
          toolset: 14.2
          arch: ${{ matrix.arch }}
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: QtCache-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.qt_version }}
      - name: Installing Qt - ${{ matrix.arch }}
        uses: jurplel/install-qt-action@v2.5.0
        with:
          version: ${{ matrix.qt_version }}
          arch: ${{ matrix.qtarch }}
          mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
# =========================================================================================================
      - name: Linux - ${{ matrix.qt_version }} - Build preparation - Install Packages 
        if: matrix.platform == 'ubuntu-16.04'
        run: |
          sudo add-apt-repository ppa:webispy/grpc
          sudo add-apt-repository ppa:carsten-uppenbrink-net/openssl
          sudo add-apt-repository ppa:savoury1/backports
          sudo apt update
          sudo apt install -y libssl-dev tree libsodium-dev ninja-build libuv1-dev
# --------------------------------------------------------
      - name: macOS - ${{ matrix.qt_version }} - Build preparation - Install Packages 
        if: matrix.platform == 'macos-latest'
        run: |
          brew reinstall libuv
          brew reinstall openssl
          brew reinstall libsodium
          brew reinstall ninja
# --------------------------------------------------------
      - name: Win-${{ matrix.arch }} - ${{ matrix.qt_version }} - Build preparation - Download Dependencies
        shell: bash
        if: matrix.platform == 'windows-latest'
        run: |
         mkdir -p ./libs
         choco install -y ninja
         curl -o ./libs/Qv2ray-deps-libsodium-${{ matrix.arch }}-windows.7z -L https://github.com/DuckVador/shadowsocksr-uvw-deps/releases/download/release/Qv2ray-deps-libsodium-${{ matrix.arch }}-windows.7z
         curl -o ./libs/Qv2ray-deps-openssl-${{ matrix.arch }}-windows.7z -L https://github.com/DuckVador/shadowsocksr-uvw-deps/releases/download/release/Qv2ray-deps-openssl-${{ matrix.arch }}-windows.7z
         curl -o ./libs/Qv2ray-deps-libuv-${{ matrix.arch }}-windows.7z -L https://github.com/DuckVador/shadowsocksr-uvw-deps/releases/download/release/Qv2ray-deps-libuv-${{ matrix.arch }}-windows.7z
      - name: Win-${{ matrix.arch }} - Build preparation - Extract Dependencies
        if: matrix.platform == 'windows-latest'
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ./libs/Qv2ray-deps-libsodium-${{ matrix.arch }}-windows.7z
          pathTarget: ./libs
      - name: Win-${{ matrix.arch }} - Build preparation - Extract Dependencies
        if: matrix.platform == 'windows-latest'
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ./libs/Qv2ray-deps-libuv-${{ matrix.arch }}-windows.7z
          pathTarget: ./libs
      - name: Win-${{ matrix.arch }} - Build preparation - Extract Dependencies
        if: matrix.platform == 'windows-latest'
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ./libs/Qv2ray-deps-openssl-${{ matrix.arch }}-windows.7z
          pathTarget: ./libs
# ========================================================================================================= Generate MakeFile and Build
      - name: macOS - ${{ matrix.qt_version }} - Generate Dependencies and Build
        shell: bash
        if: matrix.platform == 'macos-latest'
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1 -DOPENSSL_LIBRARIES=/usr/local/opt/openssl@1.1/lib -Dsodium_USE_STATIC_LIBS=1 
          cmake --build . --parallel $(sysctl -n hw.logicalcpu)
# --------------------------------------------------------        
      - name: Windows - ${{ matrix.qt_version }} - Generate Dependencies and Build
        shell: bash
        if: matrix.platform == 'windows-latest'
        env:
          CC: cl.exe
          CXX: cl.exe
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release   
          cmake --build . --parallel $(nproc)
# --------------------------------------------------------
      - name: Linux - ${{ matrix.qt_version }} - Generate Dependencies and Build
        if: matrix.platform == 'ubuntu-16.04'
        shell: bash
        env:
          CC: /usr/bin/gcc-9
          CXX: /usr/bin/g++-9
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -Dsodium_USE_STATIC_LIBS=1 
          cmake --build . --parallel $(nproc)
